//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public class BloodSoulMarkBoxUI : MonoBehaviour
{
	public UISprite m_lockFrame;
	public UISprite m_add;
	public UISprite m_icon;
	public UISprite m_normalFrame;
	public UISprite m_nameBg;
	public UILabel m_name;
}

