//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public class CreateTeamSystemUIManager : MonoBehaviour
{
	public Transform m_uiSelGender;

	public Transform m_uiSelHero;

    public UIInput m_name;

	int m_genderId = 1;
    int m_playerImgId = 850117;

	int m_heroId;

	void Start()
	{
        string playerName = MonoInstancePool.getInstance<UserData>().teamName;
        if (string.IsNullOrEmpty(playerName))
        {
            ShowSelImg();
        }
        else
		{
            ShowSelHero();
		}
	}

	void ShowSelGender()
	{
		if (m_uiSelGender)
		{
			m_uiSelGender.gameObject.SetActive(true);
		}
		if (m_uiSelHero)
		{
			m_uiSelHero.gameObject.SetActive(false);
		}
	}

    public void ShowSelImg()
    {
        if (m_uiSelGender)
        {
            m_uiSelGender.gameObject.SetActive(true);
        }
        if (m_uiSelHero)
        {
            m_uiSelHero.gameObject.SetActive(false);
        }
    }

    public void ShowSelHero()
	{
		if (m_uiSelGender)
		{
			m_uiSelGender.gameObject.SetActive(false);
		}
		if (m_uiSelHero)
		{
			m_uiSelHero.gameObject.SetActive(true);
		}
	}

	public void SetGenderID(int id)
	{
		m_genderId = id;
	}

    public void SetPlayerImgID(int id)
    {
        m_playerImgId = id;
    }

	public void SetHeroID(int id)
	{
		m_heroId = id;
	}

	public void SelectGenderConfirm()
	{
        Debug.Log("select image id " + m_playerImgId + ", player name " + m_name.value);
        MonoInstancePool.getInstance<SendMessageHander>().SendCreatePlayerRequest(m_playerImgId, m_name.value);
		//ShowSelHero();
	}

	public void SelectHeroConfirm()
	{
        Debug.Log("select team hero id "+ m_heroId);
        MonoInstancePool.getInstance<SendMessageHander>().SendPlayerSelectHeroRequest(m_heroId);
	}
}

