//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;

public class CreateTeamNameInput : MonoBehaviour
{
	public UIButton m_btnConfirm;

	public RandomName m_randomName;

	//public UILabel m_lblInput;
	UIInput mInput;

	// Use this for initialization
	void Start () {
		mInput = GetComponent<UIInput>();
	}
	
	// Update is called once per frame
	void Update () {
		
	}

	public void OnChange()
	{
		CheckInputEmpty();
	}

	public void OnDeselect()
	{
		if (mInput)
		{
			string text = NGUIText.StripSymbols(mInput.value);
			if (string.IsNullOrEmpty(text))
			{
				mInput.value = m_randomName.GetRandomName();
			}
		}

		CheckInputEmpty();
	}

	void CheckInputEmpty()
	{
		//if (m_lblInput)
		if (mInput)
		{
			//if (m_lblInput.text.Length == 0)
			string text = NGUIText.StripSymbols(mInput.value);
			if (string.IsNullOrEmpty(text))
			{
				m_btnConfirm.isEnabled = false;
			}
			else
			{
				if (!m_btnConfirm.isEnabled)
				{
					m_btnConfirm.isEnabled = true;
				}
			}
		}
	}
}

